name: MQTT Test

on:
  push:
  pull_request:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Mosquitto (MQTT Broker)
        run: sudo apt-get update && sudo apt-get install -y mosquitto mosquitto-clients

      - name: Start Mosquitto
        run: nohup mosquitto > mosquitto.log 2>&1 &

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install pytest paho-mqtt

      - name: Run Tests
        run: pytest test_mqtt.py
